version: "3.9"

services:

  webserver:
    container_name: ${CONTAINER_PREFIX:-docker}-nginx

    restart: always

    build:
      context: .docker
      dockerfile: nginx.dockerfile

    volumes:
      - "./.docker/nginx/logs:/var/log/nginx"
      - "./.docker/nginx/conf.d:/etc/nginx/conf.d"
      - "${PUBLIC_ROOT_PATH:-./html}:/var/www/html"

    ports:
      - "${NGINX_FORWARD_HOST_PORT:-80}:80"
      - "${NGINX_FORWARD_SSL_PORT:-443}:443"

    depends_on:
      - docker_php
      - docker_mysql
      - docker_redis

    external_links:
      # Programming Language Containers
      - "${CONTAINER_PREFIX:-docker}-php:docker_php"
      - "${CONTAINER_PREFIX:-docker}-mysql:docker_mysql"
      - "${CONTAINER_PREFIX:-docker}-redis:docker_redis"

    networks:
      - WebServer

  php:
    container_name: ${CONTAINER_PREFIX:-docker}-php

    restart: unless-stopped

    build:
      context: .docker
      dockerfile: php.dockerfile

    volumes:
      - "${PUBLIC_ROOT_PATH:-./html}:/var/www/html"

    ports:
      - "9000:9000"

    networks:
      - WebServer

  mysql:
    container_name: ${CONTAINER_PREFIX:-docker}-mysql

    restart: unless-stopped

    build:
      context: .docker
      dockerfile: mysql.dockerfile

    command: --default-authentication-plugin=mysql_native_password

    ports:
      - "${MYSQL_FORWARD_DB_PORT:-3306}:3306"

    volumes:
      - "./.docker/mysql/data:/var/lib/mysql"
      - "./.docker/mysql/conf.d:/etc/mysql/conf.d"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}

    networks:
      - WebServer

  postgresql:
    container_name: "${CONTAINER_PREFIX:-docker}-postgresql"

    build:
      context: .docker
      dockerfile: postgresql.dockerfile

    restart: unless-stopped

    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

    volumes:
      - postgresql:/var/lib/postgresql/data

    ports:
      - "${PGSQL_FORWARD_DB_PORT:-5432}:5432"

  redis:
    container_name: ${CONTAINER_PREFIX:-docker}-redis

    build:
      context: .docker
      dockerfile: redis.dockerfile

    restart: unless-stopped

    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"

    volumes:
      - "./.docker/redis/data:/data"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

    networks:
      - WebServer

networks:
  WebServer:
    driver: "${NETWORKS:-bridge}"

volumes:
  postgresql:
