version: "3.9"

services:

  # *******************************************
  #     Nginx Service Container
  # *******************************************
  nginx:
    container_name: ${CONTAINER_PREFIX:-docker}-nginx
    
    restart: always
    
    build:
      context: .docker
      dockerfile: nginx.dockerfile

    ports:
      - "${NGINX_FORWARD_SSL_PORT:-443}:443"
      - "${NGINX_FORWARD_HOST_PORT:-80}:80"
    
    volumes:
      - ${CONTEXT_PATH:-./.docker}/nginx/conf.d:/etc/nginx/conf.d
      - ${CONTEXT_PATH:-./.docker}/nginx/logs:/var/log/nginx
      - ${PUBLIC_ROOT_PATH:-./html}:/var/www/html

    depends_on:
      - php
      - mysql

    external_links:
      # Programming Language Containers
      - "${CONTAINER_PREFIX:-docker}-php:php"
      - "${CONTAINER_PREFIX:-docker}-mysql:mysql"
    
    network_mode: ${NETWORKS:-bridge}


  # *******************************************
  #     PHP FPM Service Container
  # *******************************************
  php:
    container_name: ${CONTAINER_PREFIX:-docker}-php

    build:
      context: .docker
      dockerfile: php.dockerfile
    
    volumes:
      - ${PUBLIC_ROOT_PATH:-./html}:/var/www/html

    network_mode: ${NETWORKS:-bridge}


  # *******************************************
  #     MYSQL Service Container
  # *******************************************
  mysql:
    container_name: ${CONTAINER_PREFIX:-docker}-mysql

    build:
      context: .docker
      dockerfile: mysql.dockerfile

    ports:
      - ${MYSQL_FORWARD_DB_PORT:-3306}:3306

    volumes:
      - ${CONTEXT_PATH:-./.docker}/mysql/data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}

    network_mode: ${NETWORKS:-bridge}
